common:
  readmore: "更多"
  empty_data: "没有更多数据了"
index:
  page_title: "polarphp - 全新的 PHP 语言编译器与运行时"
  slogan: "全新的 PHP 语言编译器与运行时"
  get_started: "开始学习"
  gitee_repo: "Gitee 仓库"
  github_repo: "Github 仓库"
  features: "特性"
  feature_oop: "类似 JDK 的面向对象设计"
  feature_oop_desc: "我们使用面向对象的风格去设计，采用类似 JDK 的方式去重新组织 PHP 函数，接口和类。给 PHP 开发者提供一套设计良好并且值得信赖的编程接口，同时我们完全兼容 PHP 语言本身的语法和语义，让开发使用熟悉的感觉去开发。"
  feature_thread: "原生多线程支持"
  feature_thread_desc: "默认开启虚拟机多线程支持，提供标准的线程相关的操作原语支持，如线程创建，线程同步以及针对线程的并发编程模式的封装，让您在 PHP 中使用多线程来提高应用程序的性能同时又不过多的增加编程的复杂度。"
  feature_performance: "高性能"
  feature_performance_desc: "polarphp 容器和标准库使用现代的 C++ 语言进行开发，同时从一些开源项目借鉴了很多设计理念，标准库内核使用大家推崇异步编程架构，然后将操作系统和 C++ 标准库的功能开放给 PHP 空间，从而提升 PHP 应用程序的性能。"
  feature_doc: "完善文档支持"
  feature_doc_desc: "一个好的开源项目文档必须完善，polarphp 会在官网上给开发者提供完善的标准库用户手册和 API 编程文档，让您快速学习上手，从容的掌握每一个设计细节。"
  feature_cpp11: "基于 C++17 标准开发"
  feature_cpp11_desc: "polarphp 运行时和标准库本身是一个比较大的 C++ 项目，我们在实现的时候特别注意项目的架构设计，代码的阅读性以及项目的可维护性，C++17 标准的很多特性能够帮助我们实现这些设计目标，从而带给内核开发者以及 PHP 用户空间一个可以依赖的代码基础。"
  fearure_opensource: "开放源代码"
  feature_opensource_desc: "polarphp 是一个采用 Apache Licence 2.0 协议的开源项目，源代码托管在 github 和 gitee 平台，您可以放心的部署 polarphp 运行时并且在其基础上运行 PHP 应用程序，一切都是自由的。"
  tutorials: "快速入门"
  latest_posts: "最新博客"
  empty_list: "没有数据"
  sponsor_title: "赞助者"
  become_sponsor: "如何赞助"
  developer_title: "开发者"
  become_developer: "如何参与开发"
  partner_title: "合作伙伴"
  become_partner: "成为合作伙伴"
  links_title: "友情链接"
manual:
  page_title_suffix: " - polarphp 开发手册"
community:
  page_title: "遇见 polarphp 项目开发者社区"
  nomember: "目前暂时没有社区开发者，欢迎加入我们。"
  meet_community: "遇见 polarphp 开发者社区"
  contribute_types: "我们需要下面几种类型的社区贡献者："
  cpp_developer: "核心 C++ 开发伙伴"
  manual_writter: "入门文档和手册维护与更新伙伴"
  website_maintainer: "官网网站维护与开发伙伴"
  demo_application_developer: "例子项目开发伙伴"
  community_sermon: "polarphp 社区布道师"
  interesting_desc: "如果您对上面任何一项感兴趣，请联系我们："
  core_community_title: "核心开发者成员"

  core_community_desc: "polarphp 项目及其生态环境由一群对 PHP 感兴趣的国际性的社区伙伴进行开发，我们在下面列举出一部分主要贡献的开发者。"
  community_community_title: "社区开发者成员"
  community_community_desc: "一些 polarphp 的社区成员让这里变得更加丰富多彩，有必要在此特别提及。我们与这些主要合作伙伴建立了更加亲密的关系，经常与他们就即将到来的功能和新闻展开协作。"
blog:
  page_title: "欢迎访问 polarphp 项目博客"
  site_navbar_leaf: "文章正文"
post:
  page_title_suffix: "polarphp 项目博客"
about:
  page_title: "关于我们"
  page_changelog_title: "polarphp 更新日志"
  page_become_sponsor_title: "Help us to become a sponsor of polarphp project"
  page_become_developer_title: "Come with us let the polarphp project better"
  page_become_partner_title: "Become a partner and let more people know about polarphp project"
  menu_become_sponsor: "赞助"
  menu_become_developer: "参与开发"
  menu_become_partner: "成为合作伙伴"
  menu_changelog: "更新记录"
  menu_aboutus: "关于我们"
