common:
  readmore: "更多"
  empty_data: "没有更多数据了"
index:
  page_title: "polarphp - The runtime container of PHP programming language"
  slogan: "The runtime container of PHP programming language"
  get_started: "快速入门"
  gitee_repo: "Gitee仓库"
  github_repo: "Github仓库"
  features: "特性"
  feature_oop: "OOP design like JDK"
  feature_oop_desc: "We develop polarphp with object oriented programming style, reorganize PHP functions, interface and classes like Java JDK style. To provide developer with a well designed and robust programming interface."
  feature_thread: "Thread safe support"
  feature_thread_desc: "Care about multithread environment, almost all of API are thread safe implementation. You can develop multithread application happily with polarphp, use operation system thread mechanism to improve application performance."
  feature_performance: "High performance"
  feature_performance_desc: "polarphp develop with modern C++ language and deliver to PHP developer as PHP native extension. We borrow many function and class implemention from JDK, C++ standard library and PHP kernel source code. We implment polarphp as fast as we can."
  feature_doc: "Complete documentation"
  feature_doc_desc: "A good opensource project must be well documented, polarphp supply a complete programming manuals and application programming interface documentations online. You can learn polarphp easily by manuals and get API detail usage in API documentations."
  feature_cpp11: "Implement with C++11"
  feature_cpp11_desc: "polarphp itself is big project develop with C++, We use modern C++ standard when coding and very care about the project architecture, code readability and maintainability. Provide application developer with a reliable framework codebase."
  fearure_opensource: "Opensource project"
  feature_opensource_desc: "polarphp is an opensource project adopt the Apache Licence 2.0 licence and code managed with Github platform, You can develope application with polarphp carefree, Just enjoy it!"
  tutorials: "快速入门"
  latest_posts: "最新博客"
  empty_list: "没有数据"
  sponsor_title: "赞助者"
  become_sponsor: "如何赞助"
  developer_title: "开发者"
  become_developer: "如何参与开发"
  partner_title: "合作伙伴"
  become_partner: "成为合作伙伴"
  links_title: "友情链接"
manual:
  page_title_suffix: " - polarphp develop manual"
team:
  page_title: "Meet the developer guys of polarphp project"
  nomember: "oops, current no developer from the community, very welcome to join us."
  meet_team: "Meet the Team"
  contribute_types: "We need these types of contributors:"
  cpp_developer: "Core CPP developer"
  manual_writter: "get started and manual writer"
  website_maintainer: "Official website maintainer"
  demo_application_developer: "Demo application developer"
  community_sermon: "Community sermon for polarphp"
  interesting_desc: "If you are interested in any kind of work in the list above, please contact me:"
  core_team_title: "The Core Team"
  core_team_desc: "The development of polarphp and its ecosystem is guided by an international team, some of whom have chosen to be featured below."
  community_team_title: "The Community Contributors"
  community_team_desc: "Some members of the polarphp community have so enriched it, that they deserve special mention. We've developed a more intimate relationship with these key partners, often coordinating with them on upcoming features and news."
blog:
  page_title: "Welcome visit develop blog of polarphp project"
post:
  page_title_suffix: "polarphp develop blog"
about:
  page_title: "Detail infomation about polarphp project and qcoreteam organization"
  page_changelog_title: "Changelog about polarphp project"
  page_become_sponsor_title: "Help us to become a sponsor of polarphp project"
  page_become_developer_title: "Come with us let the polarphp project better"
  page_become_partner_title: "Become a partner and let more people know about polarphp project"
  menu_become_sponsor: "赞助"
  menu_become_developer: "参与开发"
  menu_become_partner: "成为合作伙伴"
  menu_changelog: "更新记录"
  menu_aboutus: "关于我们"
